name: capstone_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  supabase_flutter: ^1.10.25
  group_radio_button: ^1.3.0
  flashy_tab_bar2: ^0.0.6
  icons_plus: ^4.0.0
  image_picker: ^1.0.4
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: lib/assets/DMSans/DMSans-Regular.ttf
        - asset: lib/assets/DMSans/DMSans-Medium.ttf
          weight: 500
        - asset: lib/assets/DMSans/DMSans-SemiBold.ttf
          weight: 600
        - asset: lib/assets/DMSans/DMSans-Bold.ttf
          weight: 700
  # fonts:
  #   - family: cabin
  #     fonts:
  #       - asset: lib/assets/Cabin_Condensed/CabinCondensed-Regular.ttf
  #       - asset: lib/assets/Cabin_Condensed/CabinCondensed-Medium.ttf
  #         weight: 500
  #       - asset: lib/assets/Cabin_Condensed/CabinCondensed-SemiBold.ttf
  #         weight: 600
  #       - asset: lib/assets/Cabin_Condensed/CabinCondensed-Bold.ttf
  #         weight: 700
  assets:
  - lib/assets/

 

